//! Minimal JSON parser and string escaper, std only.
//!
//! fswreck writes its own manifests, so the emitter lives in [`crate::manifest`]
//! and stays trivial. The parser here implements the full JSON grammar anyway
//! (escapes, surrogate pairs, exponents) because manifests get hand-edited,
//! checked into repos, and regenerated by other tools — a parser that only
//! accepts its own output rots fast.

/// A parsed JSON value. Objects preserve key order.
#[derive(Debug, Clone, PartialEq)]
pub enum Value {
    Null,
    Bool(bool),
    Num(f64),
    Str(String),
    Arr(Vec<Value>),
    Obj(Vec<(String, Value)>),
}

impl Value {
    pub fn get(&self, key: &str) -> Option<&Value> {
        match self {
            Value::Obj(pairs) => pairs.iter().find(|(k, _)| k == key).map(|(_, v)| v),
            _ => None,
        }
    }

    pub fn as_str(&self) -> Option<&str> {
        match self {
            Value::Str(s) => Some(s),
            _ => None,
        }
    }

    /// Integer view. JSON numbers are f64, exact only up to 2^53 — fswreck
    /// stores anything that may exceed that (the u64 seed) as a string.
    pub fn as_u64(&self) -> Option<u64> {
        match self {
            Value::Num(n) if n.fract() == 0.0 && *n >= 0.0 && *n <= 9_007_199_254_740_992.0 => {
                Some(*n as u64)
            }
            _ => None,
        }
    }

    pub fn as_arr(&self) -> Option<&[Value]> {
        match self {
            Value::Arr(items) => Some(items),
            _ => None,
        }
    }
}

/// Parse a complete JSON document. Trailing non-whitespace is an error.
pub fn parse(input: &str) -> Result<Value, String> {
    let mut p = Parser {
        b: input.as_bytes(),
        i: 0,
    };
    p.skip_ws();
    let v = p.value()?;
    p.skip_ws();
    if p.i != p.b.len() {
        return Err(format!("trailing data at byte {}", p.i));
    }
    Ok(v)
}

/// Escape a string for embedding in a JSON document (no surrounding quotes).
pub fn escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out
}

struct Parser<'a> {
    b: &'a [u8],
    i: usize,
}

impl<'a> Parser<'a> {
    fn skip_ws(&mut self) {
        while matches!(self.b.get(self.i), Some(b' ' | b'\t' | b'\n' | b'\r')) {
            self.i += 1;
        }
    }

    fn err(&self, msg: &str) -> String {
        format!("{msg} at byte {}", self.i)
    }

    fn value(&mut self) -> Result<Value, String> {
        match self.b.get(self.i) {
            Some(b'{') => self.object(),
            Some(b'[') => self.array(),
            Some(b'"') => Ok(Value::Str(self.string()?)),
            Some(b't') => self.literal("true", Value::Bool(true)),
            Some(b'f') => self.literal("false", Value::Bool(false)),
            Some(b'n') => self.literal("null", Value::Null),
            Some(c) if c.is_ascii_digit() || *c == b'-' => self.number(),
            Some(_) => Err(self.err("unexpected character")),
            None => Err(self.err("unexpected end of input")),
        }
    }

    fn literal(&mut self, word: &str, v: Value) -> Result<Value, String> {
        if self.b[self.i..].starts_with(word.as_bytes()) {
            self.i += word.len();
            Ok(v)
        } else {
            Err(self.err("invalid literal"))
        }
    }

    fn number(&mut self) -> Result<Value, String> {
        let start = self.i;
        if self.b.get(self.i) == Some(&b'-') {
            self.i += 1;
        }
        while matches!(
            self.b.get(self.i),
            Some(b'0'..=b'9' | b'.' | b'e' | b'E' | b'+' | b'-')
        ) {
            self.i += 1;
        }
        let text = std::str::from_utf8(&self.b[start..self.i]).unwrap();
        text.parse::<f64>()
            .map(Value::Num)
            .map_err(|_| format!("invalid number {text:?} at byte {start}"))
    }

    fn string(&mut self) -> Result<String, String> {
        self.i += 1; // opening quote
        let mut out = String::new();
        loop {
            match self.b.get(self.i) {
                None => return Err(self.err("unterminated string")),
                Some(b'"') => {
                    self.i += 1;
                    return Ok(out);
                }
                Some(b'\\') => {
                    self.i += 1;
                    match self.b.get(self.i) {
                        Some(b'"') => out.push('"'),
                        Some(b'\\') => out.push('\\'),
                        Some(b'/') => out.push('/'),
                        Some(b'n') => out.push('\n'),
                        Some(b't') => out.push('\t'),
                        Some(b'r') => out.push('\r'),
                        Some(b'b') => out.push('\u{8}'),
                        Some(b'f') => out.push('\u{c}'),
                        Some(b'u') => {
                            let cp = self.hex4()?;
                            let c = if (0xD800..0xDC00).contains(&cp) {
                                // High surrogate: a \uXXXX low surrogate must follow.
                                if self.b.get(self.i + 1..self.i + 3) != Some(b"\\u") {
                                    return Err(self.err("lone high surrogate"));
                                }
                                self.i += 2;
                                let lo = self.hex4()?;
                                if !(0xDC00..0xE000).contains(&lo) {
                                    return Err(self.err("invalid low surrogate"));
                                }
                                let combined = 0x10000 + ((cp - 0xD800) << 10) + (lo - 0xDC00);
                                char::from_u32(combined)
                                    .ok_or_else(|| self.err("invalid surrogate pair"))?
                            } else {
                                char::from_u32(cp).ok_or_else(|| self.err("invalid \\u escape"))?
                            };
                            out.push(c);
                        }
                        _ => return Err(self.err("invalid escape")),
                    }
                    self.i += 1;
                }
                Some(&c) if c < 0x20 => return Err(self.err("raw control byte in string")),
                Some(_) => {
                    // Copy one UTF-8 scalar. The input is a &str, so slicing
                    // at char boundaries is safe.
                    let rest = std::str::from_utf8(&self.b[self.i..])
                        .map_err(|_| self.err("invalid UTF-8"))?;
                    let c = rest.chars().next().unwrap();
                    out.push(c);
                    self.i += c.len_utf8();
                }
            }
        }
    }

    fn hex4(&mut self) -> Result<u32, String> {
        let hex = self
            .b
            .get(self.i + 1..self.i + 5)
            .ok_or_else(|| self.err("truncated \\u escape"))?;
        let s = std::str::from_utf8(hex).map_err(|_| self.err("invalid \\u escape"))?;
        let v = u32::from_str_radix(s, 16).map_err(|_| self.err("invalid \\u escape"))?;
        self.i += 4;
        Ok(v)
    }

    fn array(&mut self) -> Result<Value, String> {
        self.i += 1; // '['
        let mut items = Vec::new();
        self.skip_ws();
        if self.b.get(self.i) == Some(&b']') {
            self.i += 1;
            return Ok(Value::Arr(items));
        }
        loop {
            self.skip_ws();
            items.push(self.value()?);
            self.skip_ws();
            match self.b.get(self.i) {
                Some(b',') => self.i += 1,
                Some(b']') => {
                    self.i += 1;
                    return Ok(Value::Arr(items));
                }
                _ => return Err(self.err("expected ',' or ']'")),
            }
        }
    }

    fn object(&mut self) -> Result<Value, String> {
        self.i += 1; // '{'
        let mut pairs = Vec::new();
        self.skip_ws();
        if self.b.get(self.i) == Some(&b'}') {
            self.i += 1;
            return Ok(Value::Obj(pairs));
        }
        loop {
            self.skip_ws();
            if self.b.get(self.i) != Some(&b'"') {
                return Err(self.err("expected string key"));
            }
            let key = self.string()?;
            self.skip_ws();
            if self.b.get(self.i) != Some(&b':') {
                return Err(self.err("expected ':'"));
            }
            self.i += 1;
            self.skip_ws();
            let val = self.value()?;
            pairs.push((key, val));
            self.skip_ws();
            match self.b.get(self.i) {
                Some(b',') => self.i += 1,
                Some(b'}') => {
                    self.i += 1;
                    return Ok(Value::Obj(pairs));
                }
                _ => return Err(self.err("expected ',' or '}'")),
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_scalars_including_negatives_and_exponents() {
        assert_eq!(parse("null").unwrap(), Value::Null);
        assert_eq!(parse("true").unwrap(), Value::Bool(true));
        assert_eq!(parse(" false ").unwrap(), Value::Bool(false));
        assert_eq!(parse("42").unwrap(), Value::Num(42.0));
        assert_eq!(parse("-3.5").unwrap(), Value::Num(-3.5));
        assert_eq!(parse("1e3").unwrap(), Value::Num(1000.0));
    }

    #[test]
    fn parses_strings_with_standard_escapes() {
        assert_eq!(
            parse(r#""a\n\t\"\\b""#).unwrap(),
            Value::Str("a\n\t\"\\b".into())
        );
    }

    #[test]
    fn parses_unicode_escapes_and_surrogate_pairs() {
        // BMP escape.
        assert_eq!(parse(r#""\u00e9""#).unwrap(), Value::Str("\u{e9}".into()));
        // Raw UTF-8 passes through untouched.
        assert_eq!(
            parse("\"caf\u{e9}\"").unwrap(),
            Value::Str("caf\u{e9}".into())
        );
        // U+1F600 written as a \u surrogate pair.
        assert_eq!(
            parse(r#""\ud83d\ude00""#).unwrap(),
            Value::Str("\u{1F600}".into())
        );
    }

    #[test]
    fn rejects_lone_surrogates() {
        assert!(parse(r#""\ud83d""#).is_err());
        assert!(parse(r#""\ud83dA""#).is_err());
    }

    #[test]
    fn parses_nested_arrays_and_objects_preserving_key_order() {
        let v = parse(r#"{"b":[1,2],"a":{"x":null}}"#).unwrap();
        match &v {
            Value::Obj(pairs) => {
                assert_eq!(pairs[0].0, "b");
                assert_eq!(pairs[1].0, "a");
            }
            other => panic!("expected object, got {other:?}"),
        }
        assert_eq!(v.get("b").unwrap().as_arr().unwrap().len(), 2);
        assert_eq!(parse("[]").unwrap(), Value::Arr(vec![]));
        assert_eq!(parse("{}").unwrap(), Value::Obj(vec![]));
    }

    #[test]
    fn rejects_malformed_documents() {
        assert!(parse("{} x").is_err(), "trailing garbage accepted");
        assert!(parse("1 2").is_err());
        assert!(parse(r#""abc"#).is_err(), "unterminated string accepted");
        assert!(parse("{\"a\":}").is_err());
        assert!(parse("[1,]").is_err(), "trailing comma accepted");
        assert!(parse("nul").is_err());
    }

    #[test]
    fn as_u64_guards_against_float_truncation() {
        assert_eq!(parse("32").unwrap().as_u64(), Some(32));
        assert_eq!(parse("3.5").unwrap().as_u64(), None);
        assert_eq!(parse("-1").unwrap().as_u64(), None);
    }

    #[test]
    fn escape_round_trips_through_the_parser() {
        let nasty = "quote\" back\\ tab\t nl\n ctrl\u{1} caf\u{e9}";
        let doc = format!("\"{}\"", escape(nasty));
        assert_eq!(parse(&doc).unwrap(), Value::Str(nasty.into()));
    }
}
